= CV Łukasz Lenart

:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
:pdf-page-size: A4

Applicant:
    Łukasz Lenart

Born:
    1975
Status:
    married, two children
Contact info:
    +48 606 323 122
    lukasz@lenart.org.pl
    http://www.lenart.org.pl/
Main area of interest:
    Java, Scala, JavaScript, Design Patterns, Application Architecture, Board games, Role Playing Games, Books

Projects:

Name:
    Collateral system
Client:
    South African Bank
    re-engineering project of already existing application with additional new functions
Technology used:
    JEE 6, JSF 2.0, JPA 2.0, JBoss Server 6, JAX-WS, DB2, SVN
Period:
    January 2011 – 2013
Role:
    Developer

Name:
    Document workflow system
Client:
    Polish start-up
    swing based desktop client for file synchronization and server REST API
Technology used:
    JSE 6, Swing, RESTeasy (client & server), TorqueBox, IntelliJ IDEA, MySQL / Amazon Cloud, Git
Period:
    January 2011 – April 2011
Role: Developer

Name:
    Alarm systems monitoring
Client: 
    Australian Telecommunication Company
    allows to monitor home alarm systems and takes action base on defined rules set like sending sms, e-mail or calling over VoIP
Technology used:
    JEE 6, JSF 2.0, JPA 2.0, JBoss Server 6/5, REST, SIP Servlet / Mobicents, Drools, IntelliJ IDEA, MySQL / Amazon Cloud, Subversion
Period: 
    September 2010 – January 2011
Role: 
    Developer

Name:
    Advice system
Client: 
    Danish Bank
    supports customer needs analysis and proposes solutions to accomplish them – new retirement funds, insurances, loans
Technology used:
    J2EE 1.4, Struts 1, Hibernate 3, Axis2, IntelliJ IDEA, WebLogic 8.1, DB2, Mainframe, Windows Server 2003, CVS/Subversion
Period:
    April 2008 – September 2010
Role:
    J2EE Consultant

Name:
    Insurance offers system
Client: 
    Danish Bank
    web interface to Mainframe system allows to prepare insurance offer for private and business customers
Technology used:
    J2EE 1.4, Struts 1, Axis2, IntelliJ IDEA, WebLogic 8.1, Mainframe, Windows Server 2003, CVS
Period:
    September 2007 - April 2008
Role:
    J2EE Consultant

Name:
    Shop floor efficiency monitoring
Client:
    Automotive company
    collects and analyses production data to generate compressive reports for top management, presents the production counters
Technology used:
    Borland Delphi, JEE 5, Struts 1, Spring 2, Hibernate 3, Tomcat, Linux, SQL Server 2005, Windows Server 2003, Subversion
Period:
    January 2003 – April 2006
Role:
    Software Developer

Name:
    Document workflow system
Client:
    Automotive company
    dedicated workflow system to optimize and speed up document flow between different departments
Technology used:
    Borland Delphi, JEE 5, Struts 1, Spring 2, Hibernate 3, Tomcat, Linux, SQL Server 2005, Windows Server 2003, Subversion
Period:
    February 2006 – June 2007
Role:
    Software Developer

Name:
    Werahouse management
Client:
    Automotive company
    manages warehouse space, on-fly stocktaking, optimizations of production plans
Technology used:
    Borland Delphi, Windows Mobile 2003, .NET Compact Framework, Visual Studio 2005, SQL Server 2005, Subversion
Period:
    January 2006 – September 2006
Role:
    Software Developer

Name:
    HR support system
Client:
    Automotive company
    manages employee trainings and developments of personal business plan
Technology used:
    PHP 4, MySQL, Subversion
Period:
    March 2005 – September 2005
Role:
    Software Developer

Career:
    2010 - current SoftwareMill - Developer
    2007 - 2010	   7N / Nykredit - J2EE Consultant
    2007           CSC Poland - Application Developer
    2006 - 2007	   Delphi Poland SA – GDG EMEA -  Web/Workflow/Office Developer
    2002 - 2006	   Delphi Poland SA - Global Infrastructure Services – Infrastructure Engineer
    1999 - 2002	   Delphi Poland SA - Information Systems & Services Engineer
    1998 - 1999	   ZUS – Computer Systems Engineer
